<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SQKwIuqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SQKwIuq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SQKwIuq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'revisioneRepository' => ['privates', 'App\\Repository\\RevisioneRepository', 'getRevisioneRepositoryService', true],
        ], [
            'revisioneRepository' => 'App\\Repository\\RevisioneRepository',
        ]);
    }
}
