<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9ixK3aaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9ixK3aa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9ixK3aa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'VeicoliInfo' => ['privates', '.errored..service_locator.9ixK3aa.App\\Entity\\VeicoliInfo', NULL, 'Cannot autowire service ".service_locator.9ixK3aa": it needs an instance of "App\\Entity\\VeicoliInfo" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'VeicoliInfo' => 'App\\Entity\\VeicoliInfo',
            'entityManager' => '?',
        ]);
    }
}
