<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZUn_DajService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZUn.daj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZUn.daj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teste' => ['privates', '.errored..service_locator.ZUn.daj.App\\Entity\\Teste', NULL, 'Cannot autowire service ".service_locator.ZUn.daj": it needs an instance of "App\\Entity\\Teste" but this type has been excluded in "config/services.yaml".'],
            'testeRepository' => ['privates', 'App\\Repository\\TesteRepository', 'getTesteRepositoryService', true],
        ], [
            'entityManager' => '?',
            'teste' => 'App\\Entity\\Teste',
            'testeRepository' => 'App\\Repository\\TesteRepository',
        ]);
    }
}
