<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRighe3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lrecfTn.App\Entity\Righe' shared service.
     *
     * @return \App\Entity\Righe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lrecfTn": it needs an instance of "App\\Entity\\Righe" but this type has been excluded in "config/services.yaml".');
    }
}
