<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevisioneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1KI45_u.App\Entity\Revisione' shared service.
     *
     * @return \App\Entity\Revisione
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1KI45_u": it needs an instance of "App\\Entity\\Revisione" but this type has been excluded in "config/services.yaml".');
    }
}
