<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeste2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t4lviY8.App\Entity\Teste' shared service.
     *
     * @return \App\Entity\Teste
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.t4lviY8": it needs an instance of "App\\Entity\\Teste" but this type has been excluded in "config/services.yaml".');
    }
}
