<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeicoliInfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9ixK3aa.App\Entity\VeicoliInfo' shared service.
     *
     * @return \App\Entity\VeicoliInfo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9ixK3aa": it needs an instance of "App\\Entity\\VeicoliInfo" but this type has been excluded in "config/services.yaml".');
    }
}
