<?php

namespace ContainerH2IbJT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeicoliService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BF8O.4u.App\Entity\Veicoli' shared service.
     *
     * @return \App\Entity\Veicoli
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BF8O.4u": it needs an instance of "App\\Entity\\Veicoli" but this type has been excluded in "config/services.yaml".');
    }
}
