<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sz8hxipService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sz8hxip' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sz8hxip'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rpx' => ['privates', 'App\\Service\\rpx', 'getRpxService', true],
        ], [
            'rpx' => 'App\\Service\\rpx',
        ]);
    }
}
