<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A3LrhxKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A3LrhxK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A3LrhxK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'documentiRepository' => ['privates', 'App\\Repository\\DocumentiRepository', 'getDocumentiRepositoryService', true],
        ], [
            'documentiRepository' => 'App\\Repository\\DocumentiRepository',
        ]);
    }
}
