<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1KI45UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1KI45_u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1KI45_u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'revisione' => ['privates', '.errored..service_locator.1KI45_u.App\\Entity\\Revisione', NULL, 'Cannot autowire service ".service_locator.1KI45_u": it needs an instance of "App\\Entity\\Revisione" but this type has been excluded in "config/services.yaml".'],
        ], [
            'revisione' => 'App\\Entity\\Revisione',
        ]);
    }
}
