<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TEBmyqkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TEBmyqk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TEBmyqk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'righe' => ['privates', '.errored..service_locator.TEBmyqk.App\\Entity\\Righe', NULL, 'Cannot autowire service ".service_locator.TEBmyqk": it needs an instance of "App\\Entity\\Righe" but this type has been excluded in "config/services.yaml".'],
            'righeRepository' => ['privates', 'App\\Repository\\RigheRepository', 'getRigheRepositoryService', true],
        ], [
            'entityManager' => '?',
            'righe' => 'App\\Entity\\Righe',
            'righeRepository' => 'App\\Repository\\RigheRepository',
        ]);
    }
}
