<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WDXkPKwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WDXkPKw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WDXkPKw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'righeRepository' => ['privates', 'App\\Repository\\RigheRepository', 'getRigheRepositoryService', true],
        ], [
            'righeRepository' => 'App\\Repository\\RigheRepository',
        ]);
    }
}
