<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SGYNl9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SGYNl9_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SGYNl9_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lavagna' => ['privates', '.errored..service_locator.SGYNl9_.App\\Entity\\Lavagna', NULL, 'Cannot autowire service ".service_locator.SGYNl9_": it needs an instance of "App\\Entity\\Lavagna" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'lavagna' => 'App\\Entity\\Lavagna',
        ]);
    }
}
