<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumenti2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.C1zTQLE.App\Entity\Documenti' shared service.
     *
     * @return \App\Entity\Documenti
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.C1zTQLE": it needs an instance of "App\\Entity\\Documenti" but this type has been excluded in "config/services.yaml".');
    }
}
