<?php

namespace ContainerOAYZE2B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLavagna2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SGYNl9_.App\Entity\Lavagna' shared service.
     *
     * @return \App\Entity\Lavagna
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SGYNl9_": it needs an instance of "App\\Entity\\Lavagna" but this type has been excluded in "config/services.yaml".');
    }
}
