<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240106191542 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT IDENTITY NOT NULL, body VARCHAR(MAX) NOT NULL, headers VARCHAR(MAX) NOT NULL, queue_name NVARCHAR(190) NOT NULL, created_at DATETIME2(6) NOT NULL, available_at DATETIME2(6) NOT NULL, delivered_at DATETIME2(6), PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE permessi DROP CONSTRAINT FK_permessi_utenti');
        $this->addSql('ALTER TABLE permessi DROP CONSTRAINT FK_permessi_gruppi');
        $this->addSql('ALTER TABLE prighe DROP CONSTRAINT FK_prighe_occupazione');
        $this->addSql('ALTER TABLE prev_f DROP CONSTRAINT FK_prev_f_prev');
        $this->addSql('ALTER TABLE prev_s DROP CONSTRAINT FK_prev_s_prev');
        $this->addSql('ALTER TABLE anagrafe DROP CONSTRAINT FK_anagrafe_comuni');
        $this->addSql('ALTER TABLE anagrafe DROP CONSTRAINT FK_anagrafe_nazioni');
        $this->addSql('DROP TABLE tipodoc_arca');
        $this->addSql('DROP TABLE fteste');
        $this->addSql('DROP TABLE semaforo');
        $this->addSql('DROP TABLE utenti');
        $this->addSql('DROP TABLE permessi');
        $this->addSql('DROP TABLE incassi');
        $this->addSql('DROP TABLE incassi_r');
        $this->addSql('DROP TABLE stampa_lab');
        $this->addSql('DROP TABLE tipo_incasso');
        $this->addSql('DROP TABLE feste');
        $this->addSql('DROP TABLE setup');
        $this->addSql('DROP TABLE occveicoli');
        $this->addSql('DROP TABLE prighe');
        $this->addSql('DROP TABLE VeicoliInfo');
        $this->addSql('DROP TABLE comuni');
        $this->addSql('DROP TABLE metodipag');
        $this->addSql('DROP TABLE nazioni');
        $this->addSql('DROP TABLE gruppi');
        $this->addSql('DROP TABLE cs');
        $this->addSql('DROP TABLE tipo_veicoli');
        $this->addSql('DROP TABLE aliquote');
        $this->addSql('DROP TABLE preventivi');
        $this->addSql('DROP TABLE fcorpi');
        $this->addSql('DROP TABLE disp_veicoli');
        $this->addSql('DROP TABLE autisti');
        $this->addSql('DROP TABLE gruppo_veicoli');
        $this->addSql('DROP TABLE stato_occupazioni');
        $this->addSql('DROP TABLE stato_fatture_occupazioni');
        $this->addSql('DROP TABLE banca');
        $this->addSql('DROP TABLE occrighe_default');
        $this->addSql('DROP TABLE preventivi_r');
        $this->addSql('DROP TABLE occupazione');
        $this->addSql('DROP TABLE frighe');
        $this->addSql('DROP TABLE occrighe');
        $this->addSql('DROP TABLE cc');
        $this->addSql('DROP TABLE ass');
        $this->addSql('DROP TABLE prev');
        $this->addSql('DROP TABLE prev_f');
        $this->addSql('DROP TABLE prev_s');
        $this->addSql('DROP TABLE occrighesenza');
        $this->addSql('DROP TABLE occrighecon');
        $this->addSql('DROP TABLE dtproperties');
        $this->addSql('DROP TABLE prev_i');
        $this->addSql('DROP TABLE prev_x');
        $this->addSql('DROP TABLE clienti');
        $this->addSql('DROP TABLE anagrafe');
        $this->addSql('DROP TABLE note_giorno');
        $this->addSql('DROP TABLE fteste_descr');
        $this->addSql('DROP TABLE pagamenti');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN data_lavagna DATETIME2(6)');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN dc DATETIME2(6) NOT NULL');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN uc INT NOT NULL');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN dm DATETIME2(6) NOT NULL');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN um INT NOT NULL');
        $this->addSql('ALTER TABLE lavagna ADD CONSTRAINT FK_6B896A5BC72AAFAE FOREIGN KEY (uc) REFERENCES webuser (id_wu)');
        $this->addSql('ALTER TABLE lavagna ADD CONSTRAINT FK_6B896A5B209282A9 FOREIGN KEY (um) REFERENCES webuser (id_wu)');
        $this->addSql('CREATE INDEX IDX_6B896A5BC72AAFAE ON lavagna (uc)');
        $this->addSql('CREATE INDEX IDX_6B896A5B209282A9 ON lavagna (um)');
        $this->addSql('ALTER TABLE righe ALTER COLUMN id_meccanico NVARCHAR(20)');
        $this->addSql('ALTER TABLE righe ADD CONSTRAINT FK_DE7A55E614FB0BB6 FOREIGN KEY (id_off_intervento) REFERENCES off_intervento (id_off_intervento)');
        $this->addSql('CREATE INDEX IDX_DE7A55E614FB0BB6 ON righe (id_off_intervento)');
        $this->addSql('ALTER TABLE teste ALTER COLUMN sid NVARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE teste ADD CONSTRAINT FK_E6B4490F96C37B3E FOREIGN KEY (utente_creazione) REFERENCES webuser (id_wu)');
        $this->addSql('ALTER TABLE teste ADD CONSTRAINT FK_E6B4490FBD30DEB FOREIGN KEY (utente_modifica) REFERENCES webuser (id_wu)');
        $this->addSql('CREATE INDEX IDX_E6B4490F96C37B3E ON teste (utente_creazione)');
        $this->addSql('CREATE INDEX IDX_E6B4490FBD30DEB ON teste (utente_modifica)');
        $this->addSql('ALTER TABLE veicoli DROP COLUMN descr_alias');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN id_veicolo NVARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN num_parco NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN descrizion NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN targa NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN id_tipo_veicolo NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN id_gruppo_veicolo NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN immatricolazione DATETIME2(6) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN numposti NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN dc DATETIME2(6) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN dm NVARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN descrizione2 NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN ordine NVARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN proprieta NVARCHAR(400) NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN fittizio NVARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE veicoli DROP CONSTRAINT DF_49F1981D_2FBD85FF');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN termiche NVARCHAR(255) NOT NULL');
        $this->addSql('EXEC sp_dropextendedproperty N\'MS_Description\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'veicoli\', N\'COLUMN\', id_veicolo');
        $this->addSql('EXEC sp_dropextendedproperty N\'MS_Description\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'veicoli\', N\'COLUMN\', immatricolazione');
        $this->addSql('ALTER TABLE veicoli_info DROP COLUMN targa');        
        $this->addSql('ALTER TABLE veicoli_info DROP COLUMN telaio');
        $this->addSql('ALTER TABLE veicoli_info DROP COLUMN dimensioni');
        $this->addSql('ALTER TABLE veicoli_info ALTER COLUMN id NVARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN username NVARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN email NVARCHAR(180) NOT NULL');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN roles VARCHAR(MAX) NOT NULL');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN password NVARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN is_verified BIT NOT NULL');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'(DC2Type:json)\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'webuser\', N\'COLUMN\', roles');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3BF824AE7927C74 ON webuser (email) WHERE email IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3BF824AF85E0677 ON webuser (username) WHERE username IS NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA db_accessadmin');
        $this->addSql('CREATE SCHEMA db_backupoperator');
        $this->addSql('CREATE SCHEMA db_datareader');
        $this->addSql('CREATE SCHEMA db_datawriter');
        $this->addSql('CREATE SCHEMA db_ddladmin');
        $this->addSql('CREATE SCHEMA db_denydatareader');
        $this->addSql('CREATE SCHEMA db_denydatawriter');
        $this->addSql('CREATE SCHEMA db_owner');
        $this->addSql('CREATE SCHEMA db_securityadmin');
        $this->addSql('CREATE SCHEMA dbo');
        $this->addSql('CREATE SCHEMA Gerent\\Paola');
        $this->addSql('CREATE SCHEMA grent');
        $this->addSql('CREATE TABLE tipodoc_arca (id_tipodoc NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, tipo_traffico NCHAR(1) COLLATE Latin1_General_CI_AS, id_ditta NCHAR(20) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_tipodoc))');
        $this->addSql('CREATE TABLE fteste (id_ftesta INT IDENTITY NOT NULL, id_cli NCHAR(6) COLLATE Latin1_General_CI_AS, id_tipodoc NCHAR(2) COLLATE Latin1_General_CI_AS, num_fatt INT, data_fatt DATETIME2(6), bollo NUMERIC(18, 2), acconto NUMERIC(18, 2), id_pag NCHAR(4) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), dm DATETIME2(6), imponibile NUMERIC(18, 2), iva NUMERIC(18, 2), uc NCHAR(15) COLLATE Latin1_General_CI_AS, um NCHAR(15) COLLATE Latin1_General_CI_AS, export BIT, id_autista INT, id_veicolo INT, id_gruppo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS, data_uscita DATETIME2(6), data_rientro DATETIME2(6), passeggero NCHAR(30) COLLATE Latin1_General_CI_AS, km NCHAR(5) COLLATE Latin1_General_CI_AS, fe_iddocumento NCHAR(20) COLLATE Latin1_General_CI_AS, fe_data DATETIME2(6), fe_cig NCHAR(15) COLLATE Latin1_General_CI_AS, fe_cup NCHAR(15) COLLATE Latin1_General_CI_AS, fe_tipo_dati INT, fe_codicefile NCHAR(5) COLLATE Latin1_General_CI_AS, fe_datapag DATETIME2(6), fe_ccc NVARCHAR(100) COLLATE Latin1_General_CI_AS, incassato BIT, split_payment INT, corrispettivi NCHAR(10) COLLATE Latin1_General_CI_AS, ritenuta NUMERIC(18, 2), rit_aliquota NUMERIC(18, 2), fe_causale NCHAR(200) COLLATE Latin1_General_CI_AS, id_banca NCHAR(10) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_ftesta))');
        $this->addSql('CREATE NONCLUSTERED INDEX NonClusteredIndex-20191004-180423 ON fteste (data_fatt)');
        $this->addSql('CREATE NONCLUSTERED INDEX id_cli ON fteste (id_cli)');
        $this->addSql('CREATE NONCLUSTERED INDEX export ON fteste (export)');
        $this->addSql('ALTER TABLE fteste ADD CONSTRAINT DF_4FF9F3F6_AC3D30EF DEFAULT \'0\' FOR ritenuta');
        $this->addSql('ALTER TABLE fteste ADD CONSTRAINT DF_4FF9F3F6_1FE6FA2A DEFAULT \'0\' FOR rit_aliquota');
        $this->addSql('CREATE TABLE semaforo (id_semaforo NCHAR(30) COLLATE Latin1_General_CI_AS NOT NULL, id_utente NCHAR(10) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), PRIMARY KEY (id_semaforo))');
        $this->addSql('CREATE TABLE utenti (id_utente NCHAR(15) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, password NCHAR(10) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), PRIMARY KEY (id_utente))');
        $this->addSql('CREATE TABLE permessi (id_permesso INT IDENTITY NOT NULL, id_utente NCHAR(15) COLLATE Latin1_General_CI_AS, id_gruppo NCHAR(15) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_permesso))');
        $this->addSql('CREATE INDEX IDX_5D87107CF872060D ON permessi (id_utente)');
        $this->addSql('CREATE INDEX IDX_5D87107CFB34A5C2 ON permessi (id_gruppo)');
        $this->addSql('CREATE TABLE incassi (id_incasso INT IDENTITY NOT NULL, id_cli NCHAR(7) COLLATE Latin1_General_CI_AS, data_incasso DATETIME2(6), tipo_incasso NCHAR(3) COLLATE Latin1_General_CI_AS, importo NUMERIC(18, 2), dc DATETIME2(6), uc NCHAR(20) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), um NCHAR(20) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_incasso))');
        $this->addSql('CREATE TABLE incassi_r (id_incasso_r INT IDENTITY NOT NULL, id_incasso INT NOT NULL, id_ftesta INT, importo NUMERIC(18, 2), PRIMARY KEY (id_incasso_r))');
        $this->addSql('CREATE TABLE stampa_lab (id_slab INT IDENTITY NOT NULL, ext_nid INT, ext_cid NCHAR(50) COLLATE Latin1_General_CI_AS, sid NVARCHAR(50) COLLATE Latin1_General_CI_AS, ordine INT, PRIMARY KEY (id_slab))');
        $this->addSql('CREATE TABLE tipo_incasso (id NCHAR(10) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NVARCHAR(50) COLLATE Latin1_General_CI_AS, ordine INT, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE feste (id_festa INT IDENTITY NOT NULL, dfesta DATETIME2(6), descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_festa))');
        $this->addSql('CREATE TABLE setup (id_setup NCHAR(20) COLLATE Latin1_General_CI_AS NOT NULL, cval NCHAR(254) COLLATE Latin1_General_CI_AS, nval NUMERIC(18, 2), dval DATETIME2(6), descrizion NCHAR(100) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_setup))');
        $this->addSql('CREATE TABLE occveicoli (id_occveicolo INT IDENTITY NOT NULL, id_occupazione INT, id_veicolo INT, dal DATETIME2(6), dal_dove NCHAR(250) COLLATE Latin1_General_CI_AS, al DATETIME2(6), al_dove NCHAR(250) COLLATE Latin1_General_CI_AS, km1 INT, km2 INT, PRIMARY KEY (id_occveicolo))');
        $this->addSql('CREATE TABLE prighe (id_occupazione INT, id_prighe INT IDENTITY NOT NULL, id_articolo INT, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, id_aliquota NCHAR(10) COLLATE Latin1_General_CI_AS, importo NUMERIC(18, 2), id_vincolo NCHAR(10) COLLATE Latin1_General_CI_AS, id_off_intervento INT)');
        $this->addSql('CREATE INDEX IDX_A2B80E99549690D3 ON prighe (id_occupazione)');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'codice iva arca\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'prighe\', N\'COLUMN\', id_aliquota');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'conto scarico arca\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'prighe\', N\'COLUMN\', id_vincolo');
        $this->addSql('CREATE TABLE VeicoliInfo (id INT, targa VARCHAR(50), telaio VARCHAR(50), dimensioni VARCHAR(50) COLLATE Latin1_General_CI_AS)');
        $this->addSql('CREATE TABLE comuni (id_comune NCHAR(4) COLLATE Latin1_General_CI_AS NOT NULL, comune NCHAR(240) COLLATE Latin1_General_CI_AS NOT NULL, id_regione INT, id_provincia INT, provincia NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, cod_comune NCHAR(6) COLLATE Latin1_General_CI_AS NOT NULL, cap NCHAR(5) COLLATE Latin1_General_CI_AS NOT NULL, uc NCHAR(15) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), um NCHAR(15) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), PRIMARY KEY (id_comune))');
        $this->addSql('ALTER TABLE comuni ADD CONSTRAINT DF_70A6267B_136E659C DEFAULT \'\' FOR cod_comune');
        $this->addSql('ALTER TABLE comuni ADD CONSTRAINT DF_70A6267B_993387B1 DEFAULT \'\' FOR cap');
        $this->addSql('CREATE TABLE metodipag (id_metodopag NCHAR(4) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_metodopag))');
        $this->addSql('CREATE TABLE nazioni (id_nazione NCHAR(3) COLLATE Latin1_General_CI_AS NOT NULL, nazione NCHAR(240) COLLATE Latin1_General_CI_AS NOT NULL, iso NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, uc NCHAR(15) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), um NCHAR(15) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), istat NCHAR(3) COLLATE Latin1_General_CI_AS, cod_catasto NCHAR(4) COLLATE Latin1_General_CI_AS, cee INT, PRIMARY KEY (id_nazione))');
        $this->addSql('CREATE TABLE gruppi (id_gruppo NCHAR(15) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_gruppo))');
        $this->addSql('CREATE TABLE cs (id_cs NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, codicex NCHAR(7) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_cs))');
        $this->addSql('CREATE TABLE tipo_veicoli (id_tipo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, con_autista BIT, PRIMARY KEY (id_tipo_veicolo))');
        $this->addSql('CREATE TABLE aliquote (id_aliquota NCHAR(3) COLLATE Latin1_General_CI_AS NOT NULL, natura NCHAR(4) COLLATE Latin1_General_CI_AS, codicex NCHAR(3) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_aliquota))');
        $this->addSql('CREATE TABLE preventivi (id_preventivo INT IDENTITY NOT NULL, data_preventivo DATETIME2(6), id_tipo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS, id_gruppo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS, servizio NVARCHAR(1000) COLLATE Latin1_General_CI_AS, rif_nome NVARCHAR(50) COLLATE Latin1_General_CI_AS, rif_tel NVARCHAR(20) COLLATE Latin1_General_CI_AS, rif_numero NVARCHAR(50) COLLATE Latin1_General_CI_AS, rif_data DATETIME2(6), rif_mail NCHAR(50) COLLATE Latin1_General_CI_AS, acconto NUMERIC(18, 2), data_Acconto DATETIME2(6), da DATETIME2(6), a DATETIME2(6), descr_tipo_veicolo NVARCHAR(50) COLLATE Latin1_General_CI_AS, pax_no INT, id_cli NCHAR(6) COLLATE Latin1_General_CI_AS, cliente NVARCHAR(50) COLLATE Latin1_General_CI_AS, indirizzo NVARCHAR(50) COLLATE Latin1_General_CI_AS, cap NVARCHAR(50) COLLATE Latin1_General_CI_AS, citta NVARCHAR(50) COLLATE Latin1_General_CI_AS, tel NCHAR(15) COLLATE Latin1_General_CI_AS, fax NCHAR(15) COLLATE Latin1_General_CI_AS, flag_ok BIT, dc DATETIME2(6), uc NCHAR(15) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), um NCHAR(15) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_preventivo))');
        $this->addSql('CREATE TABLE fcorpi (id_fcorpo INT IDENTITY NOT NULL, id_ftesta INT, id_occupazione INT, PRIMARY KEY (id_fcorpo))');
        $this->addSql('CREATE NONCLUSTERED INDEX id_ftesta ON fcorpi (id_ftesta)');
        $this->addSql('CREATE NONCLUSTERED INDEX id_occupazione ON fcorpi (id_occupazione)');
        $this->addSql('CREATE TABLE disp_veicoli (id_disp_veicolo INT IDENTITY NOT NULL, id_veicolo INT, dal DATETIME2(6), al DATETIME2(6), PRIMARY KEY (id_disp_veicolo))');
        $this->addSql('CREATE TABLE autisti (id_autista INT IDENTITY NOT NULL, cognome NCHAR(50) COLLATE Latin1_General_CI_AS, nome NCHAR(50) COLLATE Latin1_General_CI_AS, d_nascita DATETIME2(6), luogo_nascita NCHAR(50) COLLATE Latin1_General_CI_AS, patente NCHAR(20) COLLATE Latin1_General_CI_AS, d_patente DATETIME2(6), d_patente_a DATETIME2(6), indirizzo NCHAR(100) COLLATE Latin1_General_CI_AS, citta NCHAR(50) COLLATE Latin1_General_CI_AS, tel NCHAR(30) COLLATE Latin1_General_CI_AS, luogo NCHAR(30) COLLATE Latin1_General_CI_AS, mail NVARCHAR(100) COLLATE Latin1_General_CI_AS)');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'data scadenza\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'autisti\', N\'COLUMN\', d_patente_a');
        $this->addSql('CREATE TABLE gruppo_veicoli (id_gruppo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_gruppo_veicolo))');
        $this->addSql('CREATE TABLE stato_occupazioni (id_stato NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(20) COLLATE Latin1_General_CI_AS NOT NULL, ordine INT, PRIMARY KEY (id_stato))');
        $this->addSql('CREATE TABLE stato_fatture_occupazioni (id_stato NCHAR(2) COLLATE Latin1_General_CI_AS NOT NULL, descrizion NCHAR(20) COLLATE Latin1_General_CI_AS, ordine INT, PRIMARY KEY (id_stato))');
        $this->addSql('CREATE TABLE banca (id_banca NCHAR(10) COLLATE Latin1_General_CI_AS NOT NULL, descrizione NVARCHAR(100) COLLATE Latin1_General_CI_AS, iban NVARCHAR(50) COLLATE Latin1_General_CI_AS, ordine INT, PRIMARY KEY (id_banca))');
        $this->addSql('CREATE TABLE occrighe_default (id_occriga_default INT IDENTITY NOT NULL, codicearti NCHAR(20) COLLATE Latin1_General_CI_AS, ordine INT, conautista BIT, descr_prev NCHAR(200) COLLATE Latin1_General_CI_AS)');
        $this->addSql('CREATE TABLE preventivi_r (id_preventivo_r INT IDENTITY NOT NULL, id_preventivo INT, codicearti NCHAR(20) COLLATE Latin1_General_CI_AS, quantita INT, prezzoun NUMERIC(18, 2), prezzotot NUMERIC(18, 2), descrizion NCHAR(40) COLLATE Latin1_General_CI_AS, cod_iva NCHAR(3) COLLATE Latin1_General_CI_AS, aliquota NUMERIC(18, 2), contoscari NCHAR(2) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_preventivo_r))');
        $this->addSql('CREATE TABLE occupazione (id_occupazione INT IDENTITY NOT NULL, id_veicolo INT, id_tipo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS, id_gruppo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS, descr_tipo_veicolo NCHAR(50) COLLATE Latin1_General_CI_AS, dal DATETIME2(6), dal_dove NCHAR(250) COLLATE Latin1_General_CI_AS, al DATETIME2(6), al_dove NCHAR(250) COLLATE Latin1_General_CI_AS, al_previsto DATETIME2(6), km1 INT, km2 INT, kmpercorsi INT, id_autista INT, avvisato BIT, id_autista2 INT, id_cli NCHAR(6) COLLATE Latin1_General_CI_AS, rif_nome NCHAR(50) COLLATE Latin1_General_CI_AS, rif_tel NCHAR(20) COLLATE Latin1_General_CI_AS, passeggero NCHAR(50) COLLATE Latin1_General_CI_AS, num_persone NCHAR(10) COLLATE Latin1_General_CI_AS, servizio NCHAR(100) COLLATE Latin1_General_CI_AS, linguaggio NCHAR(10) COLLATE Latin1_General_CI_AS, note VARCHAR(MAX) COLLATE Latin1_General_CI_AS, descrizion NCHAR(50) COLLATE Latin1_General_CI_AS, tariffa NCHAR(10) COLLATE Latin1_General_CI_AS, stato NCHAR(2) COLLATE Latin1_General_CI_AS, stato_fatture NCHAR(2) COLLATE Latin1_General_CI_AS, tipo NCHAR(10) COLLATE Latin1_General_CI_AS, id_cc INT, id_parent INT, num_sostituzione INT, num_contratto NCHAR(10) COLLATE Latin1_General_CI_AS, id_metodopag NCHAR(4) COLLATE Latin1_General_CI_AS, cliente NVARCHAR(50) COLLATE Latin1_General_CI_AS, piva NCHAR(17) COLLATE Latin1_General_CI_AS, indirizzo NVARCHAR(50) COLLATE Latin1_General_CI_AS, cap NVARCHAR(50) COLLATE Latin1_General_CI_AS, citta NVARCHAR(50) COLLATE Latin1_General_CI_AS, tel NCHAR(15) COLLATE Latin1_General_CI_AS, fax NCHAR(15) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), uc NCHAR(15) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), um NCHAR(15) COLLATE Latin1_General_CI_AS, capcontanti NUMERIC(18, 2), capassegno NUMERIC(18, 2), capextradep NUMERIC(18, 2), cap_noteassegno NCHAR(50) COLLATE Latin1_General_CI_AS, id_prev_s INT, tot_caparra NUMERIC(18, 2), note_contratto1 NCHAR(100) COLLATE Latin1_General_CI_AS, note_contratto2 NCHAR(100) COLLATE Latin1_General_CI_AS, cap_notecontanti NCHAR(50) COLLATE Latin1_General_CI_AS, cap_noteextradep NCHAR(50) COLLATE Latin1_General_CI_AS, c21_importo_tot NUMERIC(18, 2), c22_importo_pagato NUMERIC(18, 2), c23_importo_anicipato NUMERIC(18, 2), garanzia SMALLINT, c22_importo_uguale SMALLINT, fe_iddocumento NCHAR(20) COLLATE Latin1_General_CI_AS, fe_data DATETIME2(6), fe_cig NCHAR(15) COLLATE Latin1_General_CI_AS, fe_cup NCHAR(15) COLLATE Latin1_General_CI_AS, fe_tipo_dati INT, fe_ccc NVARCHAR(100) COLLATE Latin1_General_CI_AS, num_preventivo NCHAR(10) COLLATE Latin1_General_CI_AS, id_t INT, fsv INT, snaut1 NCHAR(1) COLLATE Latin1_General_CI_AS, snaut2 NCHAR(1) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_occupazione))');
        $this->addSql('CREATE NONCLUSTERED INDEX NonClusteredIndex-20210514-152802 ON occupazione (dal)');
        $this->addSql('CREATE NONCLUSTERED INDEX NonClusteredIndex-20210514-152821 ON occupazione (al)');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'rientro previsto\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', al_previsto');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'km partenza veicolo\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', km1');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'km arrivo veicolo\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', km2');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'autista1 avvistao\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', avvisato');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'eventuale secondo autista\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', id_autista2');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'fatturazione\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', id_cli');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'nome \', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', passeggero');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'tipo di servizio\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', servizio');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'richiesto dall\'\'autista\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', linguaggio');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'carta di credito\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', id_cc');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'per sostituzioni, id contratto principale\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', id_parent');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'numero contratto di sostituzione\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', num_sostituzione');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'numero del contratto\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', num_contratto');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'metodo di pagamento\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'occupazione\', N\'COLUMN\', id_metodopag');
        $this->addSql('CREATE TABLE frighe (id_friga INT IDENTITY NOT NULL, id_fcorpo INT, id_ftesta INT, codicearti NCHAR(20) COLLATE Latin1_General_CI_AS, quantita NUMERIC(10, 2), prezzoun NUMERIC(18, 2), prezzotot NUMERIC(18, 2), descrizion NCHAR(40) COLLATE Latin1_General_CI_AS, cod_iva NCHAR(3) COLLATE Latin1_General_CI_AS, aliquota NUMERIC(18, 2), contoscari NCHAR(2) COLLATE Latin1_General_CI_AS, note NVARCHAR(2000) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_friga))');
        $this->addSql('CREATE NONCLUSTERED INDEX id_ftesta ON frighe (id_ftesta)');
        $this->addSql('CREATE NONCLUSTERED INDEX id_fcorpo ON frighe (id_fcorpo)');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'cod aliquota iva arca\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'frighe\', N\'COLUMN\', cod_iva');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'conto scarico arca\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'frighe\', N\'COLUMN\', contoscari');
        $this->addSql('CREATE TABLE occrighe (id_occriga INT IDENTITY NOT NULL, id_occupazione INT, codicearti NCHAR(20) COLLATE Latin1_General_CI_AS, quantita NUMERIC(10, 2), prezzoun NUMERIC(18, 2), prezzotot NUMERIC(18, 2), descrizion NCHAR(40) COLLATE Latin1_General_CI_AS, cod_iva NCHAR(3) COLLATE Latin1_General_CI_AS, aliquota NUMERIC(18, 2), contoscari NCHAR(2) COLLATE Latin1_General_CI_AS, note NVARCHAR(2000) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_occriga))');
        $this->addSql('CREATE TABLE cc (id_cc INT IDENTITY NOT NULL, n1 NCHAR(4) COLLATE Latin1_General_CI_AS, n2 NCHAR(4) COLLATE Latin1_General_CI_AS, n3 NCHAR(4) COLLATE Latin1_General_CI_AS, n4 NCHAR(4) COLLATE Latin1_General_CI_AS, n5 NCHAR(4) COLLATE Latin1_General_CI_AS, mesescad NCHAR(2) COLLATE Latin1_General_CI_AS, annoscad NCHAR(2) COLLATE Latin1_General_CI_AS, nome NCHAR(100) COLLATE Latin1_General_CI_AS, ditta NCHAR(100) COLLATE Latin1_General_CI_AS, tipo NCHAR(2) COLLATE Latin1_General_CI_AS, cf NCHAR(16) COLLATE Latin1_General_CI_AS, nome2 NCHAR(50) COLLATE Latin1_General_CI_AS, sesso NCHAR(1) COLLATE Latin1_General_CI_AS, data_nascita DATETIME2(6), comune_nascita NCHAR(40) COLLATE Latin1_General_CI_AS, provincia_nascita NCHAR(2) COLLATE Latin1_General_CI_AS, persona_fisica SMALLINT, estero SMALLINT, cod_arca NCHAR(6) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_cc))');
        $this->addSql('CREATE TABLE ass (id_ass INT IDENTITY NOT NULL, data_ass DATETIME2(6), targa NCHAR(10) COLLATE Latin1_General_CI_AS, descrizion NCHAR(150) COLLATE Latin1_General_CI_AS, prezzoun NUMERIC(18, 2), quantita NUMERIC(18, 2), prezzotot NUMERIC(18, 2), conto NCHAR(11) COLLATE Latin1_General_CI_AS, protocollo NCHAR(8) COLLATE Latin1_General_CI_AS, uc NCHAR(20) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), um NCHAR(20) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), PRIMARY KEY (id_ass))');
        $this->addSql('CREATE TABLE prev (id_prev INT IDENTITY NOT NULL, data_prev DATETIME2(6), num NCHAR(4) COLLATE Latin1_General_CI_AS, operatore NCHAR(15) COLLATE Latin1_General_CI_AS, id_cli NCHAR(6) COLLATE Latin1_General_CI_AS, id_tipo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS, id_gruppo_veicolo NCHAR(2) COLLATE Latin1_General_CI_AS, pax NCHAR(10) COLLATE Latin1_General_CI_AS, rif_nome NCHAR(50) COLLATE Latin1_General_CI_AS, rif_tel NCHAR(20) COLLATE Latin1_General_CI_AS, rif_data DATETIME2(6), rif_num NCHAR(10) COLLATE Latin1_General_CI_AS, rif_mail NCHAR(50) COLLATE Latin1_General_CI_AS, note VARCHAR(MAX) COLLATE Latin1_General_CI_AS, id_pag NCHAR(4) COLLATE Latin1_General_CI_AS, cliente NVARCHAR(50) COLLATE Latin1_General_CI_AS, piva NCHAR(17) COLLATE Latin1_General_CI_AS, indirizzo NVARCHAR(50) COLLATE Latin1_General_CI_AS, cap NCHAR(5) COLLATE Latin1_General_CI_AS, citta NVARCHAR(50) COLLATE Latin1_General_CI_AS, tel NCHAR(15) COLLATE Latin1_General_CI_AS, fax NCHAR(15) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), uc NCHAR(15) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), um NCHAR(15) COLLATE Latin1_General_CI_AS, totale NUMERIC(18, 2), cod_iva NCHAR(3) COLLATE Latin1_General_CI_AS, aliquota NUMERIC(18, 2), stato NCHAR(1) COLLATE Latin1_General_CI_AS, categoria NCHAR(30) COLLATE Latin1_General_CI_AS, cortatt NCHAR(50) COLLATE Latin1_General_CI_AS, destinazione NVARCHAR(100) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_prev))');
        $this->addSql('CREATE NONCLUSTERED INDEX data_prev ON prev (data_prev)');
        $this->addSql('CREATE NONCLUSTERED INDEX id_cli ON prev (id_cli)');
        $this->addSql('CREATE TABLE prev_f (id_prev_f INT IDENTITY NOT NULL, id_prev INT, codicearti NCHAR(20) COLLATE Latin1_General_CI_AS, quantita NUMERIC(18, 2), prezzoun NUMERIC(18, 2), prezzotot NUMERIC(18, 2), descrizion NCHAR(40) COLLATE Latin1_General_CI_AS, contoscari NCHAR(2) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_prev_f))');
        $this->addSql('CREATE INDEX IDX_FC8489E837C29457 ON prev_f (id_prev)');
        $this->addSql('CREATE TABLE prev_s (id_prev_s INT IDENTITY NOT NULL, id_prev INT, dal DATETIME2(6), dal_dove NCHAR(250) COLLATE Latin1_General_CI_AS, al DATETIME2(6), al_dove NCHAR(250) COLLATE Latin1_General_CI_AS, importo NUMERIC(18, 2), note VARCHAR(MAX) COLLATE Latin1_General_CI_AS, km NUMERIC(18, 2), pax NCHAR(10) COLLATE Latin1_General_CI_AS, occ BIT, prezzoun NUMERIC(18, 2), PRIMARY KEY (id_prev_s))');
        $this->addSql('CREATE INDEX IDX_91596D0337C29457 ON prev_s (id_prev)');
        $this->addSql('CREATE TABLE occrighesenza (id_occupazione INT NOT NULL, dayn INT, dayat NUMERIC(18, 2), daytot NUMERIC(18, 2), hourn INT, hourat NUMERIC(18, 2), hourtot NUMERIC(18, 2), weekn INT, weekat NUMERIC(18, 2), weektot NUMERIC(18, 2), kmn INT, kmat NUMERIC(18, 2), kmtot NUMERIC(18, 2), day1n INT, day1at NUMERIC(18, 2), day1tot NUMERIC(18, 2), day2n INT, day2at NUMERIC(18, 2), day2tot NUMERIC(18, 2), day3n INT, day3at NUMERIC(18, 2), day3tot NUMERIC(18, 2), rifornimento NUMERIC(18, 2), franchigia NUMERIC(18, 2), imponibile NUMERIC(18, 2), iva_perc NUMERIC(18, 2), ivatot NUMERIC(18, 2), totale NUMERIC(18, 2), capcontanti NUMERIC(18, 2), capassegno NUMERIC(18, 2), capextradep NUMERIC(18, 2), captotale NUMERIC(18, 2), saldoclient NUMERIC(18, 2), saldogrent NUMERIC(18, 2), PRIMARY KEY (id_occupazione))');
        $this->addSql('CREATE TABLE occrighecon (id_occupazione INT NOT NULL, noleggio NUMERIC(18, 2), kmn INT, kmat NUMERIC(18, 2), kmtot NUMERIC(18, 2), hourn INT, hourat NUMERIC(18, 2), hourtot NUMERIC(18, 2), notten INT, notteat NUMERIC(18, 2), nottetot NUMERIC(18, 2), autostrade NUMERIC(18, 2), park NUMERIC(18, 2), pastin INT, pastiat NUMERIC(18, 2), pastitot NUMERIC(18, 2), pernottamenti NUMERIC(18, 2), carburante NUMERIC(18, 2), imponibile NUMERIC(18, 2), iva_perc NUMERIC(18, 2), ivatot NUMERIC(18, 2), totale NUMERIC(18, 2), PRIMARY KEY (id_occupazione))');
        $this->addSql('CREATE TABLE dtproperties (id INT IDENTITY NOT NULL, property NVARCHAR(64) COLLATE Latin1_General_CI_AS NOT NULL, objectid INT, value NVARCHAR(255) COLLATE Latin1_General_CI_AS, uvalue NVARCHAR(255) COLLATE Latin1_General_CI_AS, lvalue VARBINARY(MAX), version INT NOT NULL, PRIMARY KEY (id, property))');
        $this->addSql('ALTER TABLE dtproperties ADD CONSTRAINT DF_7A33E9D8_BF1CD3C3 DEFAULT 0 FOR version');
        $this->addSql('CREATE TABLE prev_i (id_prev_i INT IDENTITY NOT NULL, id_prev INT, id_prev_s INT NOT NULL, codicearti NCHAR(20) COLLATE Latin1_General_CI_AS NOT NULL, quantita NUMERIC(10, 2), prezzoun NUMERIC(18, 2), prezzotot NUMERIC(18, 2), descrizion NCHAR(40) COLLATE Latin1_General_CI_AS, cod_iva NCHAR(3) COLLATE Latin1_General_CI_AS, aliquota NUMERIC(18, 2), contoscari NCHAR(2) COLLATE Latin1_General_CI_AS, note NVARCHAR(2000) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_prev_i))');
        $this->addSql('CREATE TABLE prev_x (id_prev_x INT IDENTITY NOT NULL, id_prev INT, codicearti NCHAR(20) COLLATE Latin1_General_CI_AS, quantita NUMERIC(18, 2), prezzoun NUMERIC(18, 2), prezzotot NUMERIC(18, 2), PRIMARY KEY (id_prev_x))');
        $this->addSql('CREATE TABLE clienti (id_cliente INT IDENTITY NOT NULL, cod_arca NCHAR(6) COLLATE Latin1_General_CI_AS, blocco INT, nota_blocco NVARCHAR(250) COLLATE Latin1_General_CI_AS, estero INT, persona_fisica INT, pf_cognome NVARCHAR(100) COLLATE Latin1_General_CI_AS, pf_nome NVARCHAR(100) COLLATE Latin1_General_CI_AS, pf_sesso NCHAR(1) COLLATE Latin1_General_CI_AS, provincia_nascita NCHAR(2) COLLATE Latin1_General_CI_AS)');
        $this->addSql('CREATE TABLE anagrafe (id_anagrafe INT IDENTITY NOT NULL, id_comune NCHAR(4) COLLATE Latin1_General_CI_AS, id_nazione NCHAR(3) COLLATE Latin1_General_CI_AS, descrizione NCHAR(100) COLLATE Latin1_General_CI_AS NOT NULL, indirizzo NCHAR(50) COLLATE Latin1_General_CI_AS, localita NCHAR(50) COLLATE Latin1_General_CI_AS, cap NCHAR(5) COLLATE Latin1_General_CI_AS, prov NCHAR(2) COLLATE Latin1_General_CI_AS, codice NCHAR(7) COLLATE Latin1_General_CI_AS NOT NULL, codicex NCHAR(20) COLLATE Latin1_General_CI_AS, codfiscale NCHAR(16) COLLATE Latin1_General_CI_AS, partiva NCHAR(17) COLLATE Latin1_General_CI_AS, contrpart NCHAR(11) COLLATE Latin1_General_CI_AS, pag NCHAR(4) COLLATE Latin1_General_CI_AS, fax NCHAR(16) COLLATE Latin1_General_CI_AS, telefono NCHAR(16) COLLATE Latin1_General_CI_AS, valuta NCHAR(3) COLLATE Latin1_General_CI_AS, intestazione VARCHAR(MAX) COLLATE Latin1_General_CI_AS, dnascita DATETIME2(6), lnascita NCHAR(60) COLLATE Latin1_General_CI_AS, email NCHAR(50) COLLATE Latin1_General_CI_AS, note_ana VARCHAR(MAX) COLLATE Latin1_General_CI_AS, blocco INT, nota_blocco NVARCHAR(250) COLLATE Latin1_General_CI_AS, estero INT, persona_fisica INT, pf_cognome NVARCHAR(100) COLLATE Latin1_General_CI_AS, pf_nome NVARCHAR(100) COLLATE Latin1_General_CI_AS, pf_sesso NCHAR(1) COLLATE Latin1_General_CI_AS, provincia_nascita NCHAR(2) COLLATE Latin1_General_CI_AS, uc NCHAR(15) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), um NCHAR(15) COLLATE Latin1_General_CI_AS, dm DATETIME2(6), fe_CodiceDestinatario NCHAR(7) COLLATE Latin1_General_CI_AS, split_pay INT, obsoleto INT, entepubblico INT, fe_pec NVARCHAR(250) COLLATE Latin1_General_CI_AS, pag_anticipo INT, intento_prot NVARCHAR(50) COLLATE Latin1_General_CI_AS, intento_data DATETIME2(6), id_banca NCHAR(10) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_anagrafe))');
        $this->addSql('CREATE INDEX IDX_CC0CAFA05F27DFBD ON anagrafe (id_comune)');
        $this->addSql('CREATE INDEX IDX_CC0CAFA02BB1824D ON anagrafe (id_nazione)');
        $this->addSql('ALTER TABLE anagrafe ADD CONSTRAINT DF_CC0CAFA0_7E68A0F8 DEFAULT 0 FOR split_pay');
        $this->addSql('ALTER TABLE anagrafe ADD CONSTRAINT DF_CC0CAFA0_4FA62E0A DEFAULT 0 FOR obsoleto');
        $this->addSql('ALTER TABLE anagrafe ADD CONSTRAINT DF_CC0CAFA0_31359999 DEFAULT 0 FOR entepubblico');
        $this->addSql('CREATE TABLE note_giorno (id_nota INT IDENTITY NOT NULL, con_autista INT, giorno DATETIME2(6), testo_nota VARCHAR(MAX) COLLATE Latin1_General_CI_AS, testo_nota_txt VARCHAR(MAX) COLLATE Latin1_General_CI_AS, uc NCHAR(15) COLLATE Latin1_General_CI_AS, dc DATETIME2(6), um NCHAR(15) COLLATE Latin1_General_CI_AS, dm DATETIME2(6))');
        $this->addSql('CREATE TABLE fteste_descr (id_ftesta INT NOT NULL, tipo NCHAR(20) COLLATE Latin1_General_CI_AS, targa NCHAR(10) COLLATE Latin1_General_CI_AS, km INT, data_uscita DATETIME2(6), data_rientro DATETIME2(6), conducente NCHAR(50) COLLATE Latin1_General_CI_AS, note NCHAR(254) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_ftesta))');
        $this->addSql('CREATE TABLE pagamenti (id_pag NCHAR(4) COLLATE Latin1_General_CI_AS NOT NULL, modalita NCHAR(4) COLLATE Latin1_General_CI_AS, descrizione NVARCHAR(50) COLLATE Latin1_General_CI_AS, partenza INT, giorni INT, codicex NCHAR(3) COLLATE Latin1_General_CI_AS, PRIMARY KEY (id_pag))');
        $this->addSql('ALTER TABLE permessi ADD CONSTRAINT FK_permessi_utenti FOREIGN KEY (id_utente) REFERENCES utenti (id_utente) ON UPDATE CASCADE ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE permessi ADD CONSTRAINT FK_permessi_gruppi FOREIGN KEY (id_gruppo) REFERENCES gruppi (id_gruppo) ON UPDATE CASCADE ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prighe ADD CONSTRAINT FK_prighe_occupazione FOREIGN KEY (id_occupazione) REFERENCES occupazione (id_occupazione) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prev_f ADD CONSTRAINT FK_prev_f_prev FOREIGN KEY (id_prev) REFERENCES prev (id_prev) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prev_s ADD CONSTRAINT FK_prev_s_prev FOREIGN KEY (id_prev) REFERENCES prev (id_prev) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE anagrafe ADD CONSTRAINT FK_anagrafe_comuni FOREIGN KEY (id_comune) REFERENCES comuni (id_comune) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE anagrafe ADD CONSTRAINT FK_anagrafe_nazioni FOREIGN KEY (id_nazione) REFERENCES nazioni (id_nazione) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE righe DROP CONSTRAINT FK_DE7A55E614FB0BB6');
        $this->addSql('DROP INDEX IDX_DE7A55E614FB0BB6 ON righe');
        $this->addSql('ALTER TABLE righe ALTER COLUMN id_meccanico NCHAR(20)');
        $this->addSql('DROP INDEX UNIQ_A3BF824AE7927C74 ON webuser');
        $this->addSql('DROP INDEX UNIQ_A3BF824AF85E0677 ON webuser');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN email NVARCHAR(180)');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN roles VARCHAR(MAX)');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN password NVARCHAR(200)');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN is_verified BIT');
        $this->addSql('ALTER TABLE webuser ALTER COLUMN username NCHAR(20)');
        $this->addSql('EXEC sp_dropextendedproperty N\'MS_Description\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'webuser\', N\'COLUMN\', roles');
        $this->addSql('ALTER TABLE lavagna DROP CONSTRAINT FK_6B896A5BC72AAFAE');
        $this->addSql('ALTER TABLE lavagna DROP CONSTRAINT FK_6B896A5B209282A9');
        $this->addSql('DROP INDEX IDX_6B896A5BC72AAFAE ON lavagna');
        $this->addSql('DROP INDEX IDX_6B896A5B209282A9 ON lavagna');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN uc INT');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN um INT');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN data_lavagna DATE');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN dc DATETIME2(6)');
        $this->addSql('ALTER TABLE lavagna ALTER COLUMN dm DATETIME2(6)');
        $this->addSql('ALTER TABLE teste DROP CONSTRAINT FK_E6B4490F96C37B3E');
        $this->addSql('ALTER TABLE teste DROP CONSTRAINT FK_E6B4490FBD30DEB');
        $this->addSql('DROP INDEX IDX_E6B4490F96C37B3E ON teste');
        $this->addSql('DROP INDEX IDX_E6B4490FBD30DEB ON teste');
        $this->addSql('ALTER TABLE teste ALTER COLUMN sid NCHAR(250)');
        $this->addSql('ALTER TABLE veicoli_info ADD targa VARCHAR(50)');       
        $this->addSql('ALTER TABLE veicoli_info ADD telaio VARCHAR(50)');
        $this->addSql('ALTER TABLE veicoli_info ADD dimensioni VARCHAR(50)');
        $this->addSql('ALTER TABLE veicoli_info ALTER COLUMN id INT IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE veicoli ADD descr_alias NCHAR(50)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN id_veicolo INT IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN num_parco NCHAR(10)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN descrizion NCHAR(50)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN targa NCHAR(10)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN id_tipo_veicolo NCHAR(2)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN id_gruppo_veicolo NCHAR(2)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN immatricolazione DATETIME2(6)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN numposti NCHAR(10)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN dc DATETIME2(6)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN dm DATETIME2(6)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN descrizione2 NVARCHAR(200)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN ordine INT');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN proprieta NCHAR(20)');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN fittizio INT');
        $this->addSql('ALTER TABLE veicoli ALTER COLUMN termiche INT');
        $this->addSql('ALTER TABLE veicoli ADD CONSTRAINT DF_49F1981D_2FBD85FF DEFAULT 0 FOR termiche');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'targa\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'veicoli\', N\'COLUMN\', id_veicolo');
        $this->addSql('EXEC sp_addextendedproperty N\'MS_Description\', N\'solo mese e anno\', N\'SCHEMA\', \'dbo\', N\'TABLE\', \'veicoli\', N\'COLUMN\', immatricolazione');
    }
}
