<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyxcmW3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyxcmW3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSyxcmW3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSyxcmW3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSyxcmW3\App_KernelProdContainer([
    'container.build_hash' => 'SyxcmW3',
    'container.build_id' => '278e3340',
    'container.build_time' => 1704746973,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSyxcmW3');
