<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AAbP0_3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.AAbP0.3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AAbP0.3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'righeRepository' => ['privates', 'App\\Repository\\RigheRepository', 'getRigheRepositoryService', true],
        ], [
            'entityManager' => '?',
            'righeRepository' => 'App\\Repository\\RigheRepository',
        ]);
    }
}
