<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQ2oDsWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.NQ2oDsW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NQ2oDsW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'rpx' => ['privates', 'App\\Service\\rpx', 'getRpxService', true],
        ], [
            'em' => '?',
            'rpx' => 'App\\Service\\rpx',
        ]);
    }
}
