<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BF8O_4uService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BF8O.4u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BF8O.4u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'veicoli' => ['privates', '.errored..service_locator.BF8O.4u.App\\Entity\\Veicoli', NULL, 'Cannot autowire service ".service_locator.BF8O.4u": it needs an instance of "App\\Entity\\Veicoli" but this type has been excluded in "config/services.yaml".'],
        ], [
            'veicoli' => 'App\\Entity\\Veicoli',
        ]);
    }
}
