<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YFuXd5aService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.yFuXd5a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yFuXd5a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'VeicoliInfo' => ['privates', '.errored..service_locator.yFuXd5a.App\\Entity\\VeicoliInfo', NULL, 'Cannot autowire service ".service_locator.yFuXd5a": it needs an instance of "App\\Entity\\VeicoliInfo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'VeicoliInfo' => 'App\\Entity\\VeicoliInfo',
        ]);
    }
}
