<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T4lviY8Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.t4lviY8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t4lviY8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'teste' => ['privates', '.errored..service_locator.t4lviY8.App\\Entity\\Teste', NULL, 'Cannot autowire service ".service_locator.t4lviY8": it needs an instance of "App\\Entity\\Teste" but this type has been excluded in "config/services.yaml".'],
        ], [
            'teste' => 'App\\Entity\\Teste',
        ]);
    }
}
