<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6gRZGGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.6gR_ZGG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6gR_ZGG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lavagna' => ['privates', '.errored..service_locator.6gR_ZGG.App\\Entity\\Lavagna', NULL, 'Cannot autowire service ".service_locator.6gR_ZGG": it needs an instance of "App\\Entity\\Lavagna" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lavagna' => 'App\\Entity\\Lavagna',
        ]);
    }
}
