<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BInhQ5LService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bInhQ5L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bInhQ5L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'veicoliRepository' => ['privates', 'App\\Repository\\VeicoliRepository', 'getVeicoliRepositoryService', true],
        ], [
            'veicoliRepository' => 'App\\Repository\\VeicoliRepository',
        ]);
    }
}
