<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLavagnaService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.6gR_ZGG.App\Entity\Lavagna' shared service.
     *
     * @return \App\Entity\Lavagna
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6gR_ZGG": it needs an instance of "App\\Entity\\Lavagna" but this type has been excluded in "config/services.yaml".');
    }
}
