<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRigheService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.TEBmyqk.App\Entity\Righe' shared service.
     *
     * @return \App\Entity\Righe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TEBmyqk": it needs an instance of "App\\Entity\\Righe" but this type has been excluded in "config/services.yaml".');
    }
}
