<?php

namespace ContainerSyxcmW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTesteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TesteRepository' shared autowired service.
     *
     * @return \App\Repository\TesteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Service\\rpx'] ?? $container->load('getRpxService'));

        if (isset($container->privates['App\\Repository\\TesteRepository'])) {
            return $container->privates['App\\Repository\\TesteRepository'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Repository\\TesteRepository'])) {
            return $container->privates['App\\Repository\\TesteRepository'];
        }

        return $container->privates['App\\Repository\\TesteRepository'] = new \App\Repository\TesteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->services['router'] ?? $container->getRouterService()), $a, $b);
    }
}
