<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Teste extends \App\Entity\Teste implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_testa', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'tipodoc', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'numero_doc', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'data_doc', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_veicolo', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_meccanico', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'tipo_intervento', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'data_creazione', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'data_modifica', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'utente_creazione', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'utente_modifica', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_t_real', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'state', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'sid', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'km_attuali', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'terminato', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'webUserCreazione', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'webUserModifica'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_testa', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'tipodoc', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'numero_doc', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'data_doc', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_veicolo', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_meccanico', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'tipo_intervento', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'data_creazione', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'data_modifica', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'utente_creazione', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'utente_modifica', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'id_t_real', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'state', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'sid', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'km_attuali', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'terminato', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'webUserCreazione', '' . "\0" . 'App\\Entity\\Teste' . "\0" . 'webUserModifica'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Teste $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getWebUserCreazione(): ?\App\Entity\WebUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebUserCreazione', []);

        return parent::getWebUserCreazione();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebUserCreazione(?\App\Entity\WebUser $webUser): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebUserCreazione', [$webUser]);

        return parent::setWebUserCreazione($webUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebUserModifica(): ?\App\Entity\WebUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebUserModifica', []);

        return parent::getWebUserModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebUserModifica(?\App\Entity\WebUser $webUser): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebUserModifica', [$webUser]);

        return parent::setWebUserModifica($webUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDoc(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDoc', []);

        return parent::getTipoDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDoc(string $tipodoc): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDoc', [$tipodoc]);

        return parent::setTipoDoc($tipodoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDoc(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDoc', []);

        return parent::getNumeroDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDoc($numero_doc): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDoc', [$numero_doc]);

        return parent::setNumeroDoc($numero_doc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataDoc(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataDoc', []);

        return parent::getDataDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataDocFormat($format): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataDocFormat', [$format]);

        return parent::getDataDocFormat($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataDoc(\DateTimeInterface $data_doc): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataDoc', [$data_doc]);

        return parent::setDataDoc($data_doc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVeicolo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVeicolo', []);

        return parent::getIdVeicolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVeicolo(int $id_veicolo): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVeicolo', [$id_veicolo]);

        return parent::setIdVeicolo($id_veicolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMeccanico(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMeccanico', []);

        return parent::getIdMeccanico();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMeccanico(int $id_meccanico): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMeccanico', [$id_meccanico]);

        return parent::setIdMeccanico($id_meccanico);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoIntervento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoIntervento', []);

        return parent::getTipoIntervento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoIntervento(string $tipo_intervento): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoIntervento', [$tipo_intervento]);

        return parent::setTipoIntervento($tipo_intervento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCreazione(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCreazione', []);

        return parent::getDataCreazione();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCreazione(\DateTimeInterface $data_creazione): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCreazione', [$data_creazione]);

        return parent::setDataCreazione($data_creazione);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModifica(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModifica', []);

        return parent::getDataModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataModifica(\DateTimeInterface $data_modifica): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataModifica', [$data_modifica]);

        return parent::setDataModifica($data_modifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtenteCreazione(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtenteCreazione', []);

        return parent::getUtenteCreazione();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtenteCreazione(int $utente_creazione): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtenteCreazione', [$utente_creazione]);

        return parent::setUtenteCreazione($utente_creazione);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtenteModifica(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtenteModifica', []);

        return parent::getUtenteModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtenteModifica(?int $utente_modifica): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtenteModifica', [$utente_modifica]);

        return parent::setUtenteModifica($utente_modifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTReal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTReal', []);

        return parent::getIdTReal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTReal(int $id_t_real): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTReal', [$id_t_real]);

        return parent::setIdTReal($id_t_real);
    }

    /**
     * {@inheritDoc}
     */
    public function getState(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState(?string $state): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getSid(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSid', []);

        return parent::getSid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSid(string $sid): \App\Entity\Teste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSid', [$sid]);

        return parent::setSid($sid);
    }

    /**
     * {@inheritDoc}
     */
    public function getKmAttuali(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKmAttuali', []);

        return parent::getKmAttuali();
    }

    /**
     * {@inheritDoc}
     */
    public function setKmAttuali(?int $km_attuali): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKmAttuali', [$km_attuali]);

        return parent::setKmAttuali($km_attuali);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerminato(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerminato', []);

        return parent::getTerminato();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerminato(?int $terminato): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerminato', [$terminato]);

        return parent::setTerminato($terminato);
    }

}
