<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lavagna extends \App\Entity\Lavagna implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'idL', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'anomalia', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'id_veicolo', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'data_lavagna', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'dc', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'uc', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'dm', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'um', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'webUserCreazione', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'webUserModifica'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'idL', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'anomalia', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'id_veicolo', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'data_lavagna', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'dc', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'uc', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'dm', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'um', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'webUserCreazione', '' . "\0" . 'App\\Entity\\Lavagna' . "\0" . 'webUserModifica'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lavagna $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdL(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdL();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdL', []);

        return parent::getIdL();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVeicolo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVeicolo', []);

        return parent::getIdVeicolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVeicolo(int $id_veicolo): \App\Entity\Lavagna
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVeicolo', [$id_veicolo]);

        return parent::setIdVeicolo($id_veicolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnomalia(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnomalia', []);

        return parent::getAnomalia();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnomalia(string $anomalia): \App\Entity\Lavagna
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnomalia', [$anomalia]);

        return parent::setAnomalia($anomalia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataLavagna(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataLavagna', []);

        return parent::getDataLavagna();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataLavagna(?\DateTimeInterface $data_lavagna): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataLavagna', [$data_lavagna]);

        return parent::setDataLavagna($data_lavagna);
    }

    /**
     * {@inheritDoc}
     */
    public function getDc(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDc', []);

        return parent::getDc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDc(\DateTimeInterface $dc): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDc', [$dc]);

        return parent::setDc($dc);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebUserCreazione(): ?\App\Entity\WebUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebUserCreazione', []);

        return parent::getWebUserCreazione();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebUserCreazione(?\App\Entity\WebUser $webUser): \App\Entity\Lavagna
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebUserCreazione', [$webUser]);

        return parent::setWebUserCreazione($webUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebUserModifica(): ?\App\Entity\WebUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebUserModifica', []);

        return parent::getWebUserModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebUserModifica(?\App\Entity\WebUser $webUser): \App\Entity\Lavagna
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebUserModifica', [$webUser]);

        return parent::setWebUserModifica($webUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getUc(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUc', []);

        return parent::getUc();
    }

    /**
     * {@inheritDoc}
     */
    public function setUc(int $uc): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUc', [$uc]);

        return parent::setUc($uc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDm(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDm', []);

        return parent::getDm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDm(\DateTimeInterface $dm): \App\Entity\Lavagna
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDm', [$dm]);

        return parent::setDm($dm);
    }

    /**
     * {@inheritDoc}
     */
    public function getUm(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUm', []);

        return parent::getUm();
    }

    /**
     * {@inheritDoc}
     */
    public function setUm(int $um): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUm', [$um]);

        return parent::setUm($um);
    }

}
