<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Righe extends \App\Entity\Righe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_riga', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_testa_fk', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_l_fk', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'descrizione_anomalia', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'descrizione_intervento', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_meccanico', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_riga_prelievo', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'data_creazione', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'data_modifica', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'utente_creazione', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'utente_modifica', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_r_real', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'stato', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_fk', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'ore', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_off_intervento'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_riga', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_testa_fk', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_l_fk', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'descrizione_anomalia', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'descrizione_intervento', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_meccanico', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_riga_prelievo', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'data_creazione', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'data_modifica', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'utente_creazione', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'utente_modifica', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_r_real', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'stato', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_fk', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'ore', '' . "\0" . 'App\\Entity\\Righe' . "\0" . 'id_off_intervento'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Righe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTestaFk(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTestaFk', []);

        return parent::getIdTestaFk();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTestaFk(int $id_testa_fk): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTestaFk', [$id_testa_fk]);

        return parent::setIdTestaFk($id_testa_fk);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLFk(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLFk', []);

        return parent::getIdLFk();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdLFk(int $id_l_fk): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdLFk', [$id_l_fk]);

        return parent::setIdLFk($id_l_fk);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescrizioneAnomalia(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescrizioneAnomalia', []);

        return parent::getDescrizioneAnomalia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescrizioneAnomalia(?string $descrizione_anomalia): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescrizioneAnomalia', [$descrizione_anomalia]);

        return parent::setDescrizioneAnomalia($descrizione_anomalia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescrizioneIntervento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescrizioneIntervento', []);

        return parent::getDescrizioneIntervento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescrizioneIntervento(?string $descrizione_intervento): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescrizioneIntervento', [$descrizione_intervento]);

        return parent::setDescrizioneIntervento($descrizione_intervento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMeccanico(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMeccanico', []);

        return parent::getIdMeccanico();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMeccanico(?string $id_meccanico): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMeccanico', [$id_meccanico]);

        return parent::setIdMeccanico($id_meccanico);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRigaPrelievo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRigaPrelievo', []);

        return parent::getIdRigaPrelievo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRigaPrelievo(?int $id_riga_prelievo): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRigaPrelievo', [$id_riga_prelievo]);

        return parent::setIdRigaPrelievo($id_riga_prelievo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCreazione(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCreazione', []);

        return parent::getDataCreazione();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCreazione(\DateTimeInterface $data_creazione): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCreazione', [$data_creazione]);

        return parent::setDataCreazione($data_creazione);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModifica(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModifica', []);

        return parent::getDataModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataModifica(?\DateTimeInterface $data_modifica): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataModifica', [$data_modifica]);

        return parent::setDataModifica($data_modifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtenteCreazione(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtenteCreazione', []);

        return parent::getUtenteCreazione();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtenteCreazione(int $utente_creazione): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtenteCreazione', [$utente_creazione]);

        return parent::setUtenteCreazione($utente_creazione);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtenteModifica(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtenteModifica', []);

        return parent::getUtenteModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtenteModifica(?int $utente_modifica): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtenteModifica', [$utente_modifica]);

        return parent::setUtenteModifica($utente_modifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRReal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRReal', []);

        return parent::getIdRReal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRReal(int $id_r_real): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRReal', [$id_r_real]);

        return parent::setIdRReal($id_r_real);
    }

    /**
     * {@inheritDoc}
     */
    public function getStato(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStato', []);

        return parent::getStato();
    }

    /**
     * {@inheritDoc}
     */
    public function setStato(?string $stato): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStato', [$stato]);

        return parent::setStato($stato);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFk(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFk', []);

        return parent::getIdFk();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFk(?int $id_fk): \App\Entity\Righe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFk', [$id_fk]);

        return parent::setIdFk($id_fk);
    }

    /**
     * {@inheritDoc}
     */
    public function getOre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOre', []);

        return parent::getOre();
    }

    /**
     * {@inheritDoc}
     */
    public function setOre(?string $ore): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOre', [$ore]);

        return parent::setOre($ore);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOffIntervento(): ?\App\Entity\OffIntervento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffIntervento', []);

        return parent::getIdOffIntervento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOffIntervento(?\App\Entity\OffIntervento $id_off_intervento): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOffIntervento', [$id_off_intervento]);

        return parent::setIdOffIntervento($id_off_intervento);
    }

}
