<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Veicoli extends \App\Entity\Veicoli implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'idVeicolo', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'numParco', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'descrizion', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'targa', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'idTipoVeicolo', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'idGruppoVeicolo', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'immatricolazione', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'numposti', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'dc', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'dm', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'descrizione2', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'ordine', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'proprieta', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'fittizio', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'termiche'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'idVeicolo', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'numParco', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'descrizion', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'targa', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'idTipoVeicolo', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'idGruppoVeicolo', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'immatricolazione', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'numposti', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'dc', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'dm', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'descrizione2', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'ordine', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'proprieta', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'fittizio', '' . "\0" . 'App\\Entity\\Veicoli' . "\0" . 'termiche'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Veicoli $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdVeicolo(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdVeicolo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVeicolo', []);

        return parent::getIdVeicolo();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumParco(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumParco', []);

        return parent::getNumParco();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumParco(?string $numParco): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumParco', [$numParco]);

        return parent::setNumParco($numParco);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescrizion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescrizion', []);

        return parent::getDescrizion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescrizion(?string $descrizion): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescrizion', [$descrizion]);

        return parent::setDescrizion($descrizion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarga(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarga', []);

        return parent::getTarga();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarga(?string $targa): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarga', [$targa]);

        return parent::setTarga($targa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoVeicolo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoVeicolo', []);

        return parent::getIdTipoVeicolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoVeicolo(?string $idTipoVeicolo): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoVeicolo', [$idTipoVeicolo]);

        return parent::setIdTipoVeicolo($idTipoVeicolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGruppoVeicolo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGruppoVeicolo', []);

        return parent::getIdGruppoVeicolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGruppoVeicolo(?string $idGruppoVeicolo): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGruppoVeicolo', [$idGruppoVeicolo]);

        return parent::setIdGruppoVeicolo($idGruppoVeicolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImmatricolazione(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImmatricolazione', []);

        return parent::getImmatricolazione();
    }

    /**
     * {@inheritDoc}
     */
    public function setImmatricolazione(?\DateTimeInterface $immatricolazione): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImmatricolazione', [$immatricolazione]);

        return parent::setImmatricolazione($immatricolazione);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumposti(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumposti', []);

        return parent::getNumposti();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumposti(?string $numposti): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumposti', [$numposti]);

        return parent::setNumposti($numposti);
    }

    /**
     * {@inheritDoc}
     */
    public function getDc(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDc', []);

        return parent::getDc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDc(?\DateTimeInterface $dc): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDc', [$dc]);

        return parent::setDc($dc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDm(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDm', []);

        return parent::getDm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDm(?\DateTimeInterface $dm): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDm', [$dm]);

        return parent::setDm($dm);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescrizione2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescrizione2', []);

        return parent::getDescrizione2();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescrizione2(?string $descrizione2): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescrizione2', [$descrizione2]);

        return parent::setDescrizione2($descrizione2);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdine(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdine', []);

        return parent::getOrdine();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdine(?int $ordine): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdine', [$ordine]);

        return parent::setOrdine($ordine);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprieta(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprieta', []);

        return parent::getProprieta();
    }

    /**
     * {@inheritDoc}
     */
    public function setProprieta(?string $proprieta): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProprieta', [$proprieta]);

        return parent::setProprieta($proprieta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFittizio(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFittizio', []);

        return parent::getFittizio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFittizio(?int $fittizio): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFittizio', [$fittizio]);

        return parent::setFittizio($fittizio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermiche(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermiche', []);

        return parent::getTermiche();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermiche(?int $termiche): \App\Entity\Veicoli
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermiche', [$termiche]);

        return parent::setTermiche($termiche);
    }

}
